# Generated by Django 5.2.1 on 2025-07-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_sale_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='expiry_date',
        ),
    ]
