"""
Django settings for meditrack project.

Generated by 'django-admin startproject' using Django 5.2.1.
"""

from pathlib import Path
import os

# ----------------------------
# Base Directory of the Project
# ----------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------
# Security Settings
# ----------------------------
# WARNING: Keep this key secret in production!
SECRET_KEY = 'django-insecure-6h3*pr%f(o0)b8#-k7+d!*4(j4jmwteo#s-vjl29mlsp$n&c^)'

# Debug mode should be False in production
DEBUG = True

# Hosts allowed to connect to this project
ALLOWED_HOSTS = []

# ----------------------------
# Application Definition
# ----------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app1'  # Your custom app
]

# ----------------------------
# Middleware Stack
# ----------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ----------------------------
# Root URL Configuration
# ----------------------------
ROOT_URLCONF = 'meditrack.urls'

# ----------------------------
# Templates Configuration
# ----------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'template')],  # Custom template folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ----------------------------
# WSGI Application
# ----------------------------
WSGI_APPLICATION = 'meditrack.wsgi.application'

# ----------------------------
# Database Configuration
# Using SQLite by default
# ----------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ----------------------------
# Password Validators
# ----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ----------------------------
# Internationalization
# ----------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True
USE_I18N = True
USE_TZ = True

# ----------------------------
# Static Files (CSS, JS, Images)
# ----------------------------
STATIC_URL = 'static/'

# ----------------------------
# Primary Key Field Type
# ----------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
